  services:
    development:
      container_name: "app-dev-client-ePayco"
      image: dev
      build:
        context: .
        target: development
      env_file:
        - .env.dev
      ports:
        - "3000:3000"
      networks:
        - ePayco-network
      volumes:
        ##- ./src:/src
        ##- ./package*.json:/package*.json
        - ./:/app
        - /app/node_modules
      restart: unless-stopped

    production:
      container_name: "app-prod-client-ePayco"
      image: prod
      build:
        context: .
        target: production
      env_file:
        - .env.prod
      ports:
        - "8000:8000"
      networks:
        - ePayco-network
      restart: unless-stopped

    ## production:
      ## container_name: "app-prod-client-ePayco"
      ## image: prod
      ## build:
        ## context: .
        ## target: production
      ## env_file:
        ## - .env.prod
      ## ports:
        ## - "8000:8000"
      ## networks:
        ## - ePayco-network
      ## restart: unless-stopped

  networks:
    ePayco-network:
      ##driver: bridge
      external: true